---
docker_artifactory_name: artifactory
docker_artifactory_image: docker.bintray.io/jfrog/artifactory-oss:6.18.1
docker_artifactory_expose:
  - '8081'
docker_artifactory_ports:
  - '8081:8081'
docker_artifactory_container_data_dir: /var/opt/jfrog/artifactory
docker_artifactory_host_data_dir: /data/artifactory/store
docker_artifactory_domainame: artifactory
docker_artifactory_directory_volumes:
  - "{{ docker_artifactory_host_data_dir }}:{{ docker_artifactory_container_data_dir }}:rw"
docker_artifactory_links: []

docker_artifactory_old_host:
docker_artifactory_new_host: 
