- name: Creating node_exporter user group
  group: name="{{groupId}}"
  become: true

- name: Creating node_exporter user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Install prometheus node exporter
  unarchive:
    src: "{{ node_version }}"
    dest: "{{ dest_path }}"
    validate_certs: false
    remote_src: yes

- name: Copy prometheus node exporter file to bin
  copy:
    src: "/tmp/node_exporter-{{ version }}.darwin-386/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Delete node exporter tmp folder
  file:
    path: '/tmp/node_exporter-{{ version }}.darwin-386'
    state: absent

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start node_exporter service
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: Check if node exporter emits metrics
  uri:
    url: http://127.0.0.1:9100/metrics
    method: GET
    status_code: 200
    body_format: json

- name: Add newly installed hosts to Prometheus
  blockinfile:
    dest: /home/alm_tools_admin/prometheus-grafana-alertmanager-example/prometheus/prometheus.yml
    marker: "## Added by ansible configuration"
    block: |2
       - job_name: '{{ ansible_hostname }}'
         scheme: http
         metrics_path: /metrics
         static_configs:
           - targets: ['{{ ansible_hostname }}:9100']
    state: present
  delegate_to: 172.25.43.131

- name: Apply changes in Prometheus
  uri:
    url: http://172.25.43.131:9090/-/reload
    method: POST
