---
- name: Create folder for postgresql exporter
  file:
    path: "{{ postgres_exporter_dest }}"
    state: directory
    mode: '0755'

- name: Unarhive and download postgres_exporter
  unarchive:
    src: "{{ postgres_exporter_src }}"
    dest: "{{ postgres_exporter_dest }}"
    remote_src: yes
    validate_certs: false

- name: Create a service postgres_exporter.service
  template: src=postgres_exporter.service.j2 dest=/etc/systemd/system/postgres_exporter.service
  notify:
    - reload systemctl
    - restart postgres_exporter


#- name: Create environment file for Postgresql
#  template: src=env.conf.j2 dest=/opt/postgres_exporter/env.conf
#  notify:
#    - reload systemctl
#    - restart postgres_exporter
